* Backups on OS X
  :PROPERTIES:
  :categories: linux,mac
  :date:     2015/03/19 18:31:45
  :updated:  2015/03/26 17:17:46
  :END:

Back to [[http://avigdev.github.io/blog/20150319/2015-03-19-backups-html/][backing up]](no pun intended), OS X uses a launchd system rather than "cron.daily". If you are like me, you probably don't want to know why and you don't care. You just want a cron.daily approach, and a way to know whether it worked or not. 

So put your bash script from [[http://avigdev.github.io/blog/20150319/2015-03-19-backups-html/][here]] somewhere on your system, and put the following script in your ~/Library/LaunchAgents/ ,  with a name like me.bckup.daily.plist (though the name should not matter, or so they tell) : 
#+BEGIN_EXAMPLE -n
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/
DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>Label</key>
<string>me.bckup.daily</string>
<key>LowPriorityIO</key>
<true/>
<key>Nice</key>
<integer>12</integer>
<key>Program</key>
<string>/path/to/your/script/bckup_to_hd</string>
<key>StartCalendarInterval</key>
<dict>
<key>Hour</key>
<integer>16</integer>
<key>Minute</key>
<integer>49</integer>
</dict>
<key>StandardErrorPath</key>
<string>/path/to/log_err_file.txt</string>
<key>StandardOutPath</key>
<string>/path/to/log_out_file.txt</string>
</dict>
</plist>
#+END_EXAMPLE
with the obvious ammendments of the exact time you want it to be launched every day, and your exact absolute paths.

To begin its action for the first time, either logout and login or :
#+BEGIN_SRC sh -n
launchctl load me.bckup.daily.plist
#+END_SRC

If something went wrong, you could use =launchctl unload= instead of =load= , get things straight and =load= again.

Now, how do you know if something went wrong ? 

first, you have your log files /path/to/log_*_file.txt . Second, you could search for clues in /private/var/log/system.log in the time you designated.
