* Xmgr annotations
  :PROPERTIES:
  :categories: xmgr
  :date:     2015/01/27 00:32:07
  :updated:  2015/01/27 00:33:39
  :END:

Frankly, I think that [[http://plasma-gate.weizmann.ac.il/Grace/][xmgr]] is obsolete. It had some grace (pun intended) 10yrs ago, and it still produces very consistent graphs. But it smells like an old cheese, it lacks latex/regexps/modern scripting language/importing of modern binary formats/2D heat maps. Nevertheless, if I happen to have an ascii data file around, I am still tempted to launch it once in every while. [[http://gmt.soest.hawaii.edu][GMT]] will take you further, but xmgr will take you faster (once you get the hang of its awkward arrangement of menus).

[[http://blog.louic.nl/?p=249][This guy]] summarizes for us some of the very basic subtleties of xmgr's gui. The most important for me are related to special chars:


The old way of including special chars/fonts :
|----------------------------------------+-----------------|
| What                                   | example         |
|----------------------------------------+-----------------|
| superscript                            | x\S2\N          |
| Subscript                              | 3\s10\N         |
| Greek letters (e.g. theta)             | \f{Symbol}q\f{} |
| Special symbols (e.g. Angstrom symbol) | \cE\C           |
|----------------------------------------+-----------------|

The new method to insert special characters in xmgrace is:

Press ctrl-e while positioned in a text-edit field to bring up the font dialog box, and select whatever you want.

Thanks [[http://blog.louic.nl/][Louic]]. 
